# Generated by Django 4.1.3 on 2022-11-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='f_feed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='l_DOB',
            field=models.DateField(null=True),
        ),
    ]
