# Generated by Django 4.1.3 on 2022-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmsapp', '0002_alter_feedback_f_feed_alter_leave_l_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='f_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
