# Generated by Django 4.1.3 on 2023-01-14 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppmsapp', '0003_alter_feedback_f_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_name', models.CharField(max_length=20, null=True)),
                ('re_feed', models.CharField(max_length=100, null=True)),
                ('re_post', models.CharField(max_length=20, null=True)),
                ('re_DOB', models.DateField(null=True)),
                ('re_status', models.CharField(max_length=20, null=True)),
                ('re_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('re_users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppmsapp.employee')),
            ],
        ),
    ]
